channels:
- defaults
- conda-forge
dependencies:
- aiohttp==3.8.1
- aiosignal==1.2.0
- alabaster==0.7.12
- alembic==1.0.10
- anaconda-project==0.10.1
- anyio==2.2.0
- appdirs==1.4.4
- applaunchservices==0.2.1
- appnope==0.1.2
- argh==0.26.2
- argon2-cffi==20.1.0
- astropy==4.2.1
- astunparse==1.6.3
- async-timeout==4.0.2
- atomicwrites==1.4.0
- attrs==20.3.0
- autopep8==1.5.6
- Babel==2.9.0
- backcall==0.2.0
- backports.tempfile==1.0
- backports.weakref==1.0.post1
- beautifulsoup4==4.9.3
- billiard==3.6.4.0
- bkcharts==0.2
- black==19.10b0
- bleach==3.3.0
- boto==2.49.0
- Bottleneck==1.3.2
- brotlipy==0.7.0
- cffi==1.14.5
- Click==7.0
- click-plugins==1.1.1
- click-repl==0.2.0
- cloudpickle==1.6.0
- clyent==1.2.2
- colorama==0.4.3
- conda==4.10.1
- conda-build==3.21.4
- conda-content-trust==0.1.1
- conda-package-handling==1.7.3
- conda-repo-cli==1.0.4
- conda-token==0.3.0
- conda-verify==3.4.2
- contextlib2==0.6.0.post1
- cryptography==2.7
- cycler==0.10.0
- Cython==0.29.23
- cytoolz==0.11.0
- dask==2021.4.0
- decorator==5.0.7
- defusedxml==0.7.1
- diff-match-patch==20200713
- dill==0.3.4
- entrypoints==0.3
- fastcache==1.1.0
- filelock==3.0.12
- flake8==3.9.2
- Flask==1.0.3
- Flask-SQLAlchemy==2.4.0
- flatbuffers==1.12
- fsspec==2022.7.1
- future==0.18.2
- gast==0.4.0
- gensim==4.1.2
- gevent==21.1.2
- glob2==0.7
- gmpy2==2.0.8
- google-pasta==0.2.0
- HeapDict==1.0.1
- html5lib==1.1
- imageio==2.9.0
- imagesize==1.2.0
- iniconfig==1.1.1
- intervaltree==3.1.0
- ipykernel==5.3.4
- ipywidgets==7.6.3
- isort==5.8.0
- itsdangerous==1.1.0
- jdcal==1.4.1
- jedi==0.18.0
- jmespath==0.9.4
- joblib==1.0.1
- json5==0.9.5
- jsonschema==3.2.0
- jupyter==1.0.0
- jupyterlab==3.0.14
- keras==2.9.0
- Keras-Preprocessing==1.1.2
- keyring==22.3.0
- kombu==5.2.2
- lazy-object-proxy==1.6.0
- libarchive-c==2.9
- locket==0.2.1
- lxml==4.6.3
- Markdown==3.4.1
- MarkupSafe==2.0.1
- matplotlib==3.4.2
- mccabe==0.6.1
- mistune==0.8.4
- mock==4.0.3
- more-itertools==8.7.0
- mpmath==1.2.1
- msgpack==1.0.2
- multidict==6.0.2
- multipledispatch==0.6.0
- navigator-updater==0.2.1
- nbclassic==0.2.6
- nbclient==0.5.3
- nbformat==5.1.3
- ndg-httpsclient==0.5.1
- nest-asyncio==1.5.1
- networkx==2.6.3
- nltk==3.6.2
- nose==1.3.7
- numexpr==2.7.3
- numpydoc==1.1.0
- oauthlib==3.2.0
- olefile==0.46
- openpyxl==3.0.7
- packaging==20.9
- pandocfilters==1.4.3
- parso==0.7.0
- partd==1.1.0
- pathspec==0.7.0
- patsy==0.5.1
- pep8==1.7.1
- pexpect==4.8.0
- pkginfo==1.7.0
- ply==3.11
- pyasn1==0.4.8
- pyasn1-modules==0.2.8
- pycosat==0.6.3
- pycparser==2.19
- pycryptodome==3.12.0
- pycurl==7.43.0.6
- Pygments
- pylint
- pyls-black
- pyls-spyder
- pyparsing==2.4.0
- pyproj==3.3.0
- pyshp==2.1.3
- pytest==6.2.3
- python-editor==1.0.4
- pytz==2019.1
- PyYAML==6.0
- pyzmq==20.0.0
- QDarkStyle==2.8.1
- QtPy==1.9.0
- s3fs==0.4.2
- scikit-learn
- seaborn
- Send2Trash
- simplegeneric==0.8.1
- snowballstemmer
- sortedcollections
- sortedcontainers
- soupsieve
- Sphinx
- sphinxcontrib-applehelp
- sphinxcontrib-devhelp
- sphinxcontrib-htmlhelp
- sphinxcontrib-jsmath
- sphinxcontrib-qthelp
- sphinxcontrib-serializinghtml
- spyder
- spyder-kernels
- tables==3.6.1
- tenacity==8.0.1
- tensorboard-data-server==0.6.1
- tensorboard-plugin-wit==1.8.1
- termcolor==1.1.0
- terminado==0.9.4
- tifffile==2020.10.1
- toml==0.10.2
- toolz==0.11.2
- tornado==6.1
- tqdm==4.62.3
- traitlets==5.1.1
- typing-extensions==4.3.0
- ujson==4.0.2
- unicodecsv==0.14.1
- vine==5.0.0
- wcwidth==0.2.5
- webencodings==0.5.1
- widgetsnbextension==3.5.1
- wrapt==1.14.1
- wurlitzer==3.0.2
- xlrd==2.0.1
- XlsxWriter==3.0.3
- xlwt==1.3.0
- xmltodict==0.12.0
- zict==2.0.0
- zipp==3.8.0
- zope.event==4.5.0
- pip
name: modiste_test
pip:
  - absl-py==1.2.0
  - amqp==5.0.7
  - anaconda-client==1.7.2
  - anaconda-navigator==2.0.3
  - appscript==1.1.1
  - asn1crypto==0.24.0
  - astroid==2.5
  - async-generator==1.10
  - backports.functools-lru-cache==1.6.4
  - backports.shutil-get-terminal-size==1.0.0
  - bitarray==1.9.2
  - bokeh==2.3.2
  - boto3==1.9.156
  - botocore==1.12.156
  - cachetools==5.2.0
  - Cartopy==0.20.1
  - celery==5.2.1
  - certifi==2019.3.9
  - chardet==3.0.4
  - charset-normalizer==2.0.9
  - click-didyoumean==0.3.0
  - cmd2==2.3.3
  - distributed==2021.4.0
  - docker==5.0.3
  - docutils==0.14
  - ElexonDataPortal==2.0.11
  - emcee==3.1.1
  - emukit==0.4.9
  - et-xmlfile==1.0.1
  - Flask-Migrate==2.5.2
  - Flask-Script==2.0.6
  - fonttools==4.28.3
  - frozenlist==1.3.0
  - google-auth==2.9.1
  - google-auth-oauthlib==0.4.6
  - GPy==1.10.0
  - greenlet==1.0.0
  - grpcio==1.47.0
  - gunicorn==19.9.0
  - gym==0.21.0
  - h5py==2.10.0
  - higher==0.2.1
  - idna==2.8
  - importlib-metadata==4.12.0
  - ipython==7.22.0
  - ipython-genutils==0.2.0
  - Jinja2==2.10.1
  - jupyter-client==6.1.12
  - jupyter-console==6.4.0
  - jupyter-core==4.7.1
  - jupyter-packaging==0.9.2
  - jupyter-server==1.6.4
  - jupyterlab-pygments==0.1.2
  - jupyterlab-server==2.4.0
  - jupyterlab-widgets==1.0.0
  - kiwisolver==1.1.0
  - libclang==14.0.1
  - llvmlite==0.36.0
  - Mako==1.0.12
  - mkl-fft==1.3.0
  - mkl-random==1.1.1
  - mkl-service==2.3.0
  - multiprocess==0.70.12.2
  - mypy-extensions==0.4.3
  - nbconvert==6.0.7
  - notebook==6.4.0
  - numba==0.53.1
  - numpy==1.20.2
  - opt-einsum==3.3.0
  - pandas==1.2.4
  - paramz==0.9.5
  - path==15.1.2
  - pathlib2==2.3.5
  - plotly==5.5.0
  - protobuf==3.19.4
  - pusher==2.1.3
  - pyaml==21.10.1
  - pyDeprecate==0.3.2
  - pygame==2.0.1
  - pylsl==1.16.0
  - pymunk==5.7.0
  - PyNaCl==1.3.0
  - pyodbc===4.0.0-unsupported
  - pyOpenSSL==19.0.0
  - pyperclip==1.8.2
  - python-dateutil==2.8.0
  - python-dotenv==0.10.3
  - pytorch-lightning==1.6.5
  - requests==2.22.0
  - requests-oauthlib==1.3.1
  - rsa==4.9
  - s3transfer==0.2.0
  - scikit-image==0.18.1
  - scikit-optimize==0.9.0
  - Shapely==1.8.0
  - six==1.12.0
  - smart-open==5.2.1
  - SQLAlchemy==1.3.4
  - statannotations==0.4.3
  - tensorboard==2.9.1
  - tensorflow==2.9.1
  - tensorflow-estimator==2.9.0
  - tensorflow-io-gcs-filesystem==0.26.0
  - teradatasql==17.10.0.4
  - teradatasqlalchemy==17.0.0.2
  - torch==1.11.0
  - torch-geometric
  - torch-scatter==2.0.9
  - torch-sparse==0.6.13
  - torchmetrics==0.9.3
  - torchvision==0.12.0
  - typed-ast==1.5.4
  - urllib3==1.25.3
  - watchdog==2.1.9
  - webdnn==1.2.11
  - websocket-client==1.2.3
  - Werkzeug==2.2.0
  - xlwings==0.23.0
  - yapf==0.32.0
  - yarl==1.7.2
  - zope.interface==5.5.0
