name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  # Include Conda packages
  - pip
  - pip:
    # List pip packages here
    - absl-py
    - aiohttp
    - aiosignal
    - alabaster
    - alembic
    - amqp
    - anaconda-client
    - anaconda-navigator
    - anaconda-project
    - anyio
    - appdirs
    - applaunchservices
    - appnope
    - appscript
    - argh
    - argon2-cffi
    - asn1crypto
    - astroid
    - astropy
    - astunparse
    - async-generator
    - async-timeout
    - atomicwrites
    - attrs
    - autopep8
    - Babel
    - backcall
    - backports.functools-lru-cache
    - backports.shutil-get-terminal-size
    - backports.tempfile
    - backports.weakref
    - beautifulsoup4
    - billiard
    - bitarray
    - bkcharts
    - black
    - bleach
    - bokeh
    - boto
    - boto3
    - botocore
    - Bottleneck
    - brotlipy
    - cachetools
    - Cartopy
    - celery
    - certifi
    - cffi
    - chardet
    - charset-normalizer
    - Click
    - click-didyoumean
    - click-plugins
    - click-repl
    - cloudpickle
    - clyent
    - cmd2
    - colorama
    - conda
    - conda-build
    - conda-content-trust
    - conda-package-handling
    - conda-repo-cli
    - conda-token
    - conda-verify
    - contextlib2
    - cryptography
    - cycler
    - Cython
    - cytoolz
    - dask
    - decorator
    - defusedxml
    - diff-match-patch
    - dill
    - distributed
    - docker
    - docutils
    - ElexonDataPortal
    - emcee
    - emukit
    - entrypoints
    - et-xmlfile
    - fastcache
    - filelock
    - flake8
    - Flask
    - Flask-Migrate
    - Flask-Script
    - Flask-SQLAlchemy
    - flatbuffers
    - fonttools
    - frozenlist
    - fsspec
    - future
    - gast
    - gensim
    - gevent
    - glob2
    - gmpy2
    - google-auth
    - google-auth-oauthlib
    - google-pasta
    - GPy
    - greenlet
    - grpcio
    - gunicorn
    - gym
    - h5py
    - HeapDict
    - higher
    - html5lib
    - idna
    - imageio
    - imagesize
    - importlib-metadata
    - iniconfig
    - intervaltree
    - ipykernel
    - ipython
    - ipython-genutils
    - ipywidgets
    - isort
    - itsdangerous
    - jdcal
    - jedi
    - Jinja2
    - jmespath
    - joblib
    - json5
    - jsonschema
    - jupyter
    - jupyter-client
    - jupyter-console
    - jupyter-core
    - jupyter-packaging
    - jupyter-server
    - jupyterlab
    - jupyterlab-server
    - jupyterlab-widgets
    - Keras
    - Keras-Preprocessing
    - keyring
    - kiwisolver
    - lazy-object-proxy
    - libarchive-c
    - llvmlite
    - locket
    - lxml
    - Markdown
    - MarkupSafe
    - matplotlib
    - mccabe
    - mistune
    - mkl-fft
    - mkl-random
    - mkl-service
    - mock
    - more-itertools
    - mpmath
    - msgpack
    - multipledispatch
    - mypy-extensions
    - navigator-updater
    - nbclassic
    - nbclient
    - nbconvert
    - nbformat
    - nest-asyncio
    - networkx
    - nltk
    - nose
    - notebook
    - numba
    - numexpr
    - numpy
    - numpydoc
    - olefile
    - openpyxl
    - opt-einsum
    - packaging
    - pandas
    - pandocfilters
    - paramiko
    - parso
    - partd
    - path
    - pathlib2
    - pathspec
    - patsy
    - pep8
    - pexpect
    - pickleshare
    - Pillow
    - pkginfo
    - pluggy
    - ply
    - prometheus-client
    - prompt-toolkit
    - protobuf
    - psutil
    - ptyprocess
    - py
    - pyasn1
    - pyasn1-modules
    - pycodestyle
    - pycosat
    - pycparser
    - pycurl
    - pydocstyle
    - pyerfa
    - pyflakes
    - Pygments
    - pylint
    - pyls-black
    - pyls-spyder
    - pynacl
    - pyodbc
    - pyOpenSSL
    - pyparsing
    - pyqt
    - PyQt5
    - PyQt5-sip
    - PyQtChart
    - PyQtWebEngine
    - pyrsistent
    - PySocks
    - pytest
    - python-dateutil
    - python-lsp-black
    - python-lsp-jsonrpc
    - python-lsp-server
    - python-slugify
    - python-utils
    - pytz
    - PyWavelets
    - pyxdg
    - PyYAML
    - pyzmq
    - QDarkStyle
    - qstylizer
    - QtAwesome
    - qtconsole
    - QtPy
    - regex
    - requests
    - requests-oauthlib
    - rope
    - rsa
    - Rtree
    - ruamel-yaml-conda
    - scikit-image
    - scikit-learn
    - scipy
    - seaborn
    - Send2Trash
    - simplegeneric
    - singledispatch
    - sip
    - six
    - sniffio
    - snowballstemmer
    - sortedcollections
    - sortedcontainers
    - soupsieve
    - Sphinx
    - sphinxcontrib-applehelp
    - sphinxcontrib-devhelp
    - sphinxcontrib-htmlhelp
    - sphinxcontrib-jsmath
    - sphinxcontrib-qthelp
    - sphinxcontrib-serializinghtml
    - sphinxcontrib-websupport
    - spyder
    - spyder-kernels
    - SQLAlchemy
    - statsmodels
    - sympy
    - tables
    - tblib
    - tensorboard
    - tensorboard-data-server
    - tensorboard-plugin-wit
    - tensorflow
    - tensorflow-addons
    - tensorflow-datasets
    - tensorflow-estimator
    - tensorflow-hub
    - tensorflow-io-gcs-filesystem
    - tensorflow-metadata
    - termcolor
    - terminado
    - testpath
    - text-unidecode
    - textdistance
    - threadpoolctl
    - three-merge
    - tifffile
    - tinycss
    - toml
    - toolz
    - tornado
    - tqdm
    - traitlets
    - typed-ast
    - typing-extensions
    - ujson
    - unicodecsv
    - urllib3
    - watchdog
    - wcwidth
    - webencodings
    - websocket-client
    - Werkzeug
    - wheel
    - widgetsnbextension
    - wrapt
    - wurlitzer
    - xlrd
    - XlsxWriter
    - xlwings
    - xlwt
    - xmltodict
    - yapf
    - yarl
    - zict
    - zipp
